Repository akitasoftware/akita-cli, pull requests merged in 2023-01, with the labels that each got.

#191 Remove apispec and upload commands
  apispec/defaults.go
  apispec/run.go
  cmd/internal/apispec/cmd.go
  cmd/internal/apispec/flags.go
  cmd/internal/legacy/sessions_checkpoint.go
  cmd/root.go
  rest/interface.go
  rest/learn_client.go
Labels: 3 – Normal Priority, Needs Review

#192 Add stub NGINX commands, and development-mode server.
  cmd/internal/nginx/dev_capture.go
  cmd/internal/nginx/nginx.go
  cmd/root.go
Labels: 4 – Low Priority, Needs Review

#193 Update akita-libs
  go.mod
  go.sum
Labels: 4 – Low Priority, Needs Review

#195 Allow user to use a proxy, an alternate server name, or skip TLS
  cmd/root.go
  rest/base_client.go
  rest/http.go
Labels: 2 – Blocking, Needs Review
